WEB-953503-Klimovich/Components/CartViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace WEB_953503_Klimovich.Components
{
    public class CartViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

WEB-953503-Klimovich/Components/MenuViewComponent.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using WEB_953503_Klimovich.Models;

namespace WEB_953503_Klimovich.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private List<MenuItem> menuItems;

        public MenuViewComponent()
        {
            menuItems = new List<MenuItem>()
            {
                new MenuItem() {Controller = "Home", Action = "Index", Text = "Lab3"},
                new MenuItem() {Controller = "Product", Action = "Index", Text = "Каталог"},
                new MenuItem() {IsPage = true, Area = "Admin", Page = "/Index", Text = "Администрирование"}
            };
        }

        public IViewComponentResult Invoke()
        {
            var controller = ViewContext.RouteData.Values["controller"];
            var area = ViewContext.RouteData.Values["area"];

            foreach (var item in menuItems)
            {
                bool isMatchingController = controller?.Equals(item.Controller) ?? false;
                bool isMatchingArea = area?.Equals(item.Area) ?? false;

                item.IsActive = isMatchingController || isMatchingArea;
            }
            return View(menuItems);
        }
    }
}

WEB-953503-Klimovich/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <a class="navbar-brand" asp-action="Index" asp-controller="Home">95350066</a>

                <div class="navbar-nav">
                    @await Component.InvokeAsync("Menu")
                </div>

                <partial name="_UserPartial" />
            </nav>
        </div>
    </header>

    <main class="container">
        @RenderBody()
    </main>

    <footer>
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="https://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="https://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="https://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>


    @RenderSection("Scripts", required: false);
    <script src="lib/jquery/dist/jquery.js"></script>
    <script src="lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</body>
</html>

WEB-953503-Klimovich/Views/Shared/_UserPartial.cshtml
@await Component.InvokeAsync("Cart")

<div class="dropdown ml-4 nav-color">
    <div class="dropdown-toggle" id="dropdownMenuButton"
         data-toggle="dropdown" aria-haspopup="true"
         aria-expanded="false">
        <img src="images/user.png" width="30"
             alt="User" class="rounded" />
    </div>
    <div class="dropdown-menu"
         aria-labelledby="dropdownMenuButton">
        <div class="dropdown-item-text">
            <img src="images/user.png" width="50" class="rounded" /> artem@gmail.com
        </div>
        <div class="dropdown-divider"></div>
        <a asp-controller="Product" asp-action="UserProducts" class="dropdown-item">Товары</a>
        <a asp-area="Identity" asp-page="/Account/Logout" class="dropdown-item">Выйти</a>
    </div>
</div>